#!/bin/bash
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# @licenselint-loose-mode

set -euo pipefail

pushd ..
make clean && make
popd

../out/cql --nolines --in cql-verify.sql --cg cql-verify.h cql-verify.c

# We do all this so that we can normalize the generated helper.  We
# want the same header shape with the OSS version of CQL and the
# internal and they have different copyright messages.  The
# test helper is part of the OSS.

sed -e "/autogenerated/d" \
    -e "/generated SignedSource/d" \
    -e "/(c).*Meta Platforms/d" <cql-verify.c >cql-verify.c2

sed -e "/autogenerated/d" \
    -e "/generated SignedSource/d" \
    -e "/(c).*Meta Platforms/d" <cql-verify.h >cql-verify.h2

(cat <<EOF; cat cql-verify.c2) >cql-verify.c
/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
EOF

(cat <<EOF; cat cql-verify.h2) >cql-verify.h
/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
EOF

rm cql-verify.h2 cql-verify.c2
